# Generated by Django 2.0.2 on 2018-04-12 11:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChildCare',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('centre_code', models.CharField(max_length=20)),
                ('centre_name', models.CharField(max_length=100)),
                ('government_subsidy', models.BooleanField()),
                ('food_offered', models.CharField(max_length=20)),
                ('second_languages_offered', models.CharField(choices=[('EN', 'English'), ('CN', 'Chinese'), ('M', 'Malay'), ('T', 'Tamil')], max_length=2)),
                ('spark_certified', models.BooleanField()),
                ('scheme_type', models.CharField(max_length=50)),
                ('iccp', models.BooleanField()),
                ('gst_registration', models.BooleanField()),
                ('centre_website', models.CharField(max_length=100)),
                ('centre_contact_no', models.CharField(max_length=20)),
                ('centre_email_address', models.EmailField(max_length=50)),
                ('centre_address', models.CharField(max_length=100)),
                ('centre_postal_code', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sg_citizen_price', models.FloatField(max_length=8)),
                ('pr_citizen_price', models.FloatField(max_length=8)),
                ('fr_citizen_price', models.FloatField(max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='Timing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday_full_day', models.CharField(max_length=20)),
                ('weekday_halfday_am', models.CharField(max_length=20)),
                ('weekday_halfday_pm', models.CharField(max_length=20)),
                ('saturday', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('infant_vacancy', models.CharField(max_length=50)),
                ('pg_vacancy', models.CharField(max_length=50)),
                ('n1_vacancy', models.CharField(max_length=50)),
                ('n2_vacancy', models.CharField(max_length=50)),
                ('k1_vacancy', models.CharField(max_length=50)),
                ('k2_vacancy', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='childcare',
            name='prices',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ChildCares.Price'),
        ),
        migrations.AddField(
            model_name='childcare',
            name='timings',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ChildCares.Timing'),
        ),
        migrations.AddField(
            model_name='childcare',
            name='vacancies',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ChildCares.Vacancy'),
        ),
    ]
