# Generated by Django 2.0.2 on 2018-04-12 17:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChildCare',
            fields=[
                ('centre_code', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('centre_name', models.CharField(max_length=100)),
                ('programmes_offered', models.CharField(max_length=50)),
                ('government_subsidy', models.CharField(max_length=20)),
                ('food_offered', models.CharField(max_length=20)),
                ('second_languages_offered', models.CharField(choices=[('EN', 'English'), ('CN', 'Chinese'), ('M', 'Malay'), ('T', 'Tamil')], max_length=2)),
                ('spark_certified', models.BooleanField()),
                ('scheme_type', models.CharField(max_length=50)),
                ('iccp', models.BooleanField()),
                ('gst_registration', models.BooleanField()),
                ('centre_website', models.CharField(max_length=100)),
                ('centre_contact_no', models.CharField(max_length=20)),
                ('centre_email_address', models.EmailField(max_length=50)),
                ('centre_address', models.CharField(max_length=100)),
                ('centre_postal_code', models.CharField(max_length=10)),
                ('centre_area', models.CharField(default='', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('citizen', models.CharField(default='', max_length=20)),
                ('price', models.FloatField(default=0.0, max_length=8)),
                ('childcare', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='ChildCares.ChildCare')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reviewer', models.CharField(max_length=50)),
                ('review', models.TextField()),
                ('childcare', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='ChildCares.ChildCare')),
            ],
        ),
        migrations.CreateModel(
            name='Timing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(max_length=30)),
                ('timing', models.CharField(max_length=20)),
                ('childcare', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timings', to='ChildCares.ChildCare')),
            ],
        ),
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vacancy_type', models.CharField(max_length=30)),
                ('vacancy', models.CharField(max_length=50)),
                ('childcare', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vacancies', to='ChildCares.ChildCare')),
            ],
        ),
    ]
