# Generated by Django 2.0.2 on 2018-04-12 12:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ChildCares', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reviewer', models.CharField(max_length=50)),
                ('review', models.TextField()),
                ('childCare', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ChildCares.ChildCare')),
            ],
        ),
    ]
