# Generated by Django 2.0.2 on 2018-04-12 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ChildCares', '0002_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='childcare',
            name='id',
        ),
        migrations.AlterField(
            model_name='childcare',
            name='centre_code',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
    ]
