# Generated by Django 2.0.2 on 2018-04-12 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ChildCares', '0003_auto_20180412_2023'),
    ]

    operations = [
        migrations.AddField(
            model_name='childcare',
            name='programmes_offered',
            field=models.CharField(default='', max_length=50),
        ),
    ]
