# Generated by Django 2.0.2 on 2018-04-12 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ChildCares', '0004_childcare_programmes_offered'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='childCare',
            new_name='centre_code',
        ),
    ]
