# Generated by Django 2.0.2 on 2018-04-12 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ChildCares', '0005_auto_20180412_2210'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='centre_code',
            new_name='childcare',
        ),
    ]
