# Generated by Django 2.0.2 on 2018-04-12 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ChildCares', '0006_auto_20180412_2210'),
    ]

    operations = [
        migrations.AddField(
            model_name='childcare',
            name='centre_remarks',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='childcare',
            name='government_subsidy',
            field=models.CharField(max_length=20),
        ),
    ]
