# Generated by Django 2.0.2 on 2018-04-12 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ChildCares', '0007_auto_20180412_2215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='childcare',
            name='centre_remarks',
            field=models.CharField(default='No remarks', max_length=50),
        ),
        migrations.AlterField(
            model_name='childcare',
            name='programmes_offered',
            field=models.CharField(max_length=50),
        ),
    ]
